### ISSUE TITLE
Installation Using Docker failed

### ISSUE THREAD

**Issue by chenwong** [miguelammatos/Kollaps#19]
hello, friend. when i install using docker, it always wrong, pls help solving it. thanks a lot. the erro info is:

error: failed retrieving file 'core.db' from mirror.rackspace.com : Could not resolve host: mirror.rackspace.com
error: failed retrieving file 'core.db' from mirror.leaseweb.net : Could not resolve host: mirror.leaseweb.net
error: failed to update core (invalid url for server)
error: failed retrieving file 'extra.db' from mirror.rackspace.com : Could not resolve host: mirror.rackspace.com
error: failed retrieving file 'extra.db' from mirror.leaseweb.net : Could not resolve host: mirror.leaseweb.net
error: failed to update extra (invalid url for server)
error: failed retrieving file 'community.db' from mirror.rackspace.com : Could not resolve host: mirror.rackspace.com
error: failed retrieving file 'community.db' from mirror.leaseweb.net : Could not resolve host: mirror.leaseweb.net
error: failed to update community (invalid url for server)
error: failed to synchronize all databases

**Comment by miguelammatos** [comment]
This seems to be a connectivity issue to the mirror.
Can you manually check if the mirror is accessible from your network?

**Comment by chenwong** [comment]
yes, it's connectivity issuse. I changed the mirror and the problem solved.
Thanks a lot.
