### ISSUE TITLE
Deploying an experiment failed when use topology.xml in examples folder

### ISSUE THREAD

**Issue by chenwong** [miguelammatos/Kollaps#20]
the error info is:
network "kollaps_network" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed

how can we creat a swarm-scoped network, friend?

**Comment by vschiavoni** [comment]
Hello Chen,
can you post here the command you used to start the experiment in question?

**Comment by chenwong** [comment]
I used the command:
docker stack deploy -c <your_experiment_name>.yaml <deployment_name>

**Comment by vschiavoni** [comment]
Can you share with us the `experiment.yaml` file please ? Feel free to hide possible confidential details.

**Comment by chenwong** [comment]
I used the topology.xml in the examples, its path is Kollapse/Kollaps-master/examples/memcached/topology.xml.

for solve this problem, i create a docker network
(1) docker network create --driver overlay kollaps_network;
(2) docker stack deploy -c mytest.yaml mytest
Creating network mytest_outside
Creating service mytest_dashboard-5bc6854d-af60-4dec-847b-6c31e3eaf191
Creating service mytest_client1-5bc6854d-af60-4dec-847b-6c31e3eaf191
Creating service mytest_client2-5bc6854d-af60-4dec-847b-6c31e3eaf191
Creating service mytest_server-5bc6854d-af60-4dec-847b-6c31e3eaf191
Creating service mytest_bootstrapper

Is this right, friend?

**Comment by chenwong** [comment]
and i don't know how to start Dashboard. can you give me some advice?

**Comment by chenwong** [comment]
[mytest.zip](https://github.com/miguelammatos/Kollaps/files/5494219/mytest.zip)
attach mytest.yaml, please help check. thanks a lot.

**Comment by vschiavoni** [comment]
@chenwong In principle, the dashboard is started automatically when launching the experiment. Did you have issue regarding this?

**Comment by chenwong** [comment]
I have some mistakes before, like i didn't creat network "kollaps_network" and i built an application failed with command "sh KollapsAppBuilder iperf3". 
Now I am trying to solve this problem.
thanks a lot.

**Comment by chenwong** [comment]
hello, friend.
if I use linux to deploy kollaps, how can i start the dashboard?
