### ISSUE TITLE
can kollaps work with linux system?

### ISSUE THREAD

**Issue by chenwong** [miguelammatos/Kollaps#21]
I try to deploy kollaps in linux system,  but i don't know how to start the dashboard.
Can kollaps work with linux system?

**Comment by chenwong** [comment]
I run the command: **docker stack deploy -c mytest.yaml mytest** and all services start. 
But my dashboard is not accessible by http://myserver-ip:8088.

**Comment by vschiavoni** [comment]
Hello Chen,

> I try to deploy kollaps in linux system, but i don't know how to start the dashboard.
> Can kollaps work with linux system?

Kollaps **only** works with Linux. Can you provide some more details about your setup (Linux distribution, kernel version) ? 

And, can you provide the output of the **docker stack** command ? Perhaps add some verbose option so that it's easier for us to understand what is going on.

**Comment by chenwong** [comment]
Linux version is 3.10.0

run **docker stack deploy -c mytest.yaml mytest**
output:
**Creating network mytest_outside
Creating service mytest_server-ebdacdc4-3f77-437c-8374-032eadd00709
Creating service mytest_bootstrapper
Creating service mytest_dashboard-ebdacdc4-3f77-437c-8374-032eadd00709
Creating service mytest_client1-ebdacdc4-3f77-437c-8374-032eadd00709
Creating service mytest_client2-ebdacdc4-3f77-437c-8374-032eadd00709
Creating service mytest_client3-ebdacdc4-3f77-437c-8374-032eadd00709**

run  **docker ps**
CONTAINER ID        IMAGE                       COMMAND                  CREATED              STATUS              PORTS               NAMES
f595bf33e434        kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_client3-ebdacdc4-3f77-437c-8374-032eadd00709.1.mcg5y18pdr1qxl047upu17zus
0d1c0c869f8a        kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_client2-ebdacdc4-3f77-437c-8374-032eadd00709.1.tli0u4stuhjturku78dhupbtm
3d051b239761        kollaps/iperf3-client:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_client1-ebdacdc4-3f77-437c-8374-032eadd00709.1.z2dx7kdxrq58ektpbw9p8wd6o
b13c34777373        5cea47c8735d                "/usr/bin/pid1 /usr/…"   About a minute ago   Up About a minute                       god_3096556972939992694
0a0ebc551821        kollaps:1.0                 "/usr/bin/pid1 /usr/…"   About a minute ago   Up About a minute                       mytest_bootstrapper.yu51boebxatondc3a2x2c2ks2.wicm3gfvwutz9ms2t5zwz4lxk
15caf16ac921        kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_server-ebdacdc4-3f77-437c-8374-032eadd00709.1.yhzbb7i6rqs6234s3z7143jaf
650b7a024539        kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_server-ebdacdc4-3f77-437c-8374-032eadd00709.3.wv3y0pfqes71m50fjvbnmnukx
5c4eaad041a9        kollaps/iperf3-server:1.0   "/bin/sh -c 'mkfifo …"   About a minute ago   Up About a minute                       mytest_server-ebdacdc4-3f77-437c-8374-032eadd00709.2.r9we7rev35cen8abfn5nyv0ru

pls help check, thanks a lot

**Comment by chenwong** [comment]
hello,vschiavoni.
A good news, I solved this problem.
My dashboard image was not created successfully before, so i can't start it.
Now it's ok now.

Thanks a lot for your help. best wishes.
