### ISSUE TITLE
how can we get topology.xml?

### ISSUE THREAD

**Issue by chenwong** [miguelammatos/Kollaps#22]
Friend, how can we get topology.xml file?

**Comment by vschiavoni** [comment]
Hello Chen,
`topology.xml ` files are provided by the Kollaps users. We provide an example here:
https://github.com/miguelammatos/Kollaps/blob/master/examples/iperf3/topology.xml 

Additional instructions are available here:
https://github.com/miguelammatos/Kollaps/tree/master/examples#topology

You should modify and customize the topology.xml according to the topology and systems that you want to use for your experiment. 
If you have issues with this, post here the topology you want to use and we'll look at it.

**Comment by chenwong** [comment]
ok, understood. Thanks a lot.
