### ISSUE TITLE
Swarm error  "kollaps_network" is declared as external, but could not be found

### ISSUE THREAD

**Issue by vschiavoni** [miguelammatos/Kollaps#24]
Following the currently published instructions to run the examples, running this:

`docker stack deploy -c iperf_docker.yaml iperf3_deployment`

the following error appears:

`When trying to use Docker swarm, I get the error "network "kollaps_network" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed”.`

(reported by INRIA team, thank you Pedro)

**Comment by vschiavoni** [comment]
This is because the topology descriptors by default assume the `kollaps_network` overlay network to be valid. For instance here https://github.com/miguelammatos/Kollaps/blob/master/examples/iperf3/topology.xml#L26 

Potential solution (pending validation) is to create the `kollaps_network` before deploying the stack: 
```
docker network create --driver=overlay --subnet=10.1.0.0/24 kollaps_network
docker stack deploy -c iperf_docker.yaml iperf3_deployment
```

**Comment by csegarragonz** [comment]
Sorry for lurking, but for some reason this popped up in my home menu and thought I would help :)

This is a part of the instructions that gets easily missed, has happened in the past, but network creation is part of the overlay setup file [here](https://github.com/miguelammatos/Kollaps/blob/master/Orchestrators.md). Which is linked from the main `README.md` right before the **Installation Using Docker** section.

**Comment by vschiavoni** [comment]
I think we should have a `TL;DR` version of the installation instructions that one cannot misunderstood. Probably deployers would appreciate a simple sequence of commands that upon completion lead to a ready-to-use system.  It could be embedded in the main `README.md`

**Comment by csegarragonz** [comment]
Ok, #27 should fix this.
