### ISSUE TITLE
Dashboard not running, w3m: Can't load http://localhost:8088. 

### ISSUE THREAD

**Issue by Zahpak** [miguelammatos/Kollaps#32]
The following error was seen in two systems:
 1- docker on wsl2 on a windows system
 2- docker desktop with linux debian 
_______________________________________________________________
Following the README file, after deploying the experiment 
```
# Deploy experiment
docker stack deploy -c topology.yaml kollaps_example
```
I tried to run the dashboard by different means, namely by running the commands:
`w3m http://localhost:8088`
or
`w3m http://127.0.0.1:8088`
or
`sensible-browser http://localhost:8088`
in wsl2 commandline 

Entering the URL in a Firefox browser of my Ubuntu dual boot system does not work either.

The prior commands had successfully been run on both systems.

**Comment by sebastiaoamaro** [comment]
Hi, @Zahpak can you run docker logs god_### where is ### is the rest of the name of the god container and put the output here.

**Comment by Zahpak** [comment]
Yes, it is. It was only based on the tutorial I followed for installing docker on wsl2. But I also had the same issue with my dual-boot. 

This is the specification for my dual-boot Ubuntu: 
`lsb_release -a`

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.4 LTS
> Release:	20.04
> Codename:	focal

_______
Bootstrapper does not show up when I run docker container ls or docker ps, but only when I run docker service ls 
Also the log for the kollaps_example_bootstrapper service returns nothing.
I can show the results in the attached picture:
![Screenshot from 2022-06-22 11-30-30](https://user-images.githubusercontent.com/37815551/174995986-7a8f7114-602f-4691-a0ac-99cc17f6106d.png)

**Comment by sebastiaoamaro** [comment]
I just did a fresh install of ubuntu 20.04 and followed the instructions there was indeed a file missing in the repo and the Kollaps image could not build properly if you pull and rebuild the Kollaps image it should work.

**Comment by Zahpak** [comment]
Yes! It's working for me as well. Thank you for your help and timely responses.
