### ISSUE TITLE
Wrong image tag in examples Deployment generator

### ISSUE THREAD

**Issue by AndreOA** [miguelammatos/Kollaps#34]
The KollapsDeploymentGenerator inside examples still points to the tag 1.0, instead of using the updated version 2.0 as mentioned in the main README

**Comment by sebastiaoamaro** [comment]
Thank you for the issue, I fixed it now and will close the issue. If you notice another mistake, or have other problems, or need help with something let us know!

**Comment by sebastiaoamaro** [comment]
Thank you for the issue, I fixed it now and will close the issue. If you notice another mistake, or have other problems, or need help with something let us know!
