### ISSUE TITLE
dashboard "start" does not start the experiment in the containers

### ISSUE THREAD

**Issue by MRandl** [miguelammatos/Kollaps#42]
Hi,
I've been going through the experiments and following the advice from the ReadMe and video series, but i'm stuck at the point where the user clicks on the "start" button in the dashboard. It tells me that all containers have "started" but when I docker ps into the containers, they are not running the executable at all. I can make them do so by running ./client.sh or ./server.sh by hand. Is that normal ?

Best,
MRandl

**Comment by sebastiaoamaro** [comment]
Hi,
Just pushed the fix for this problem. If you have other problems please let us know.
Best Regards,
Sebastião Amaro

**Comment by vschiavoni** [comment]
481628d fix his.
