### ISSUE TITLE
underscore in service name hangs the dashboard

### ISSUE THREAD

**Issue by MRandl** [miguelammatos/Kollaps#46]
Hi,
it may just be something that needs to be documented, but having an underscore in a service name in a topology will make it stuck in 'pending' mode in the dashboard. 
I can replicate it deterministically on my setup, feel free to ask if you want me to share example files for this.
Best,
MRandl

**Comment by sebastiaoamaro** [comment]
Thanks for letting us know, it is indeed a problem related to the IP lookups done when trying to find the IPs of the containers. 
Best Regards,
Sebastião Amaro
