### ISSUE TITLE
Broken link: documentation

### ISSUE THREAD

**Issue by heversonbr** [miguelammatos/Kollaps#54]
In https://kollaps.dev/docker.html , the link:

https://github.com/miguelammatos/Kollaps/blob/4a489f0e1351064a36b62901116aecd1a1162ddf/docs/install.md?plain=1#L14

points to the file : `Orchestrators.md`  that does not exist. 
It is probably a typo to `orchestrators.md`
that links to :  https://github.com/miguelammatos/Kollaps/blob/master/docs/orchestrators.md

**Comment by sebastiaoamaro** [comment]
Thanks for letting us know! 
That paragraph in itself is outdated you can follow the instructions below on the website

**Comment by sebastiaoamaro** [comment]
Closing this issue, since it is fixed.
If you any problems using Kollaps let us know!
